var blessed = require('../lib/blessed')
  , contrib = require('../')
  , screen = blessed.screen()
  , colors = require('../lib/colors')
  , markdown = contrib.markdown()

screen.append(markdown)
markdown.setOptions({ firstHeading: colors.red.italic })
markdown.setMarkdown('# Hello \n This is **markdown** printed in the `terminal` 11')
screen.render()